### ISSUE TITLE
torch.rfft error on 'Coding up model architecture page'

### ISSUE THREAD

**Issue by noahschaffer** [source-separation/tutorial#16] opened 2021-04-10 20:32 UTC
On the page for coding model architectures, `torch.rfft` is used in the following line

`fourier_basis = torch.rfft(
    torch.eye(filter_length), 
    1, onesided=True
)`

I tried to switch this to  `torch.fft.rfft`, however the argument 'onesided' no longer exists for rfft's and removing this argument yielded the following error:

`IndexError: too many indices for tensor of dimension 2`

**Comment by ethman** [comment] 2021-04-11 03:35
This is actually a duplicate of #14. I'm going to close this one in lieu of that one. Thanks for catching this!

**Closed as completed by ethman** 2021-04-11 03:35 UTC
Labels: bug
